# Generated by Django 2.2.4 on 2019-11-09 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('me_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('link', models.URLField(blank=True, verbose_name='link')),
            ],
        ),
        migrations.AddField(
            model_name='meuser',
            name='description',
            field=models.TextField(default="Don't leave this description desserted", verbose_name='body'),
        ),
        migrations.CreateModel(
            name='MePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('links', models.ManyToManyField(related_name='post_links', to='me_user.MeLink')),
            ],
        ),
    ]
